### ISSUE TITLE
Which IDEs will be supported?

### ISSUE THREAD

**Issue by ErikBjare** [lunduniversity/introprog#2]
Eclipse has been the standard in educational contexts for possibly a decade but for the past few years alternatives such as Jetbrains IDEA has grown increasingly popular in professional contexts. Is there any possibility for IDEA being presented as an alternative in the curriculum?

Jetbrains offer free educational licenses for the premium versions of their IDEs.

I could help contribute with the details if necessary.

Also: Awesome initiative with the repo, I am super-excited about having this course open source and open to PRs from students and faculty alike. I hope other teachers follow your lead!

**Comment by Powersource** [comment]
Personally, at least installing the scala ide/plugin for eclipse didn't work out very well whereas the one for IDEA works great out of the box. That's probably not a major concern for the school computers since it's install-once-properly-and-forget but students might have problems with it at home.

IDEA is both able to export and import from the eclipse project format. Although how well that works in practice I don't know. And I would suggest not using the "ultimate edition" both since the community version is open source and I would assume the premium parts aren't. But also because it is after all only an educational license meant to sell you on the product.

**Comment by bjornregnell** [comment]
@Powersource Can you explain more what was your problem when installing ScalaIDE? Did you use a fresh Eclipse Mars download and then updated it within Eclipse from here: http://scala-ide.org/download/current.html  as shown in the video clip?

**Comment by ErikBjare** [comment]
I'm closing this issue, I think the clear anwer for now is: We aim to be IDE agnostic, but we use Eclipse primarily and becoming IDE agnostic is not a short-term goal. Hopefully we can put a note somewhere in the compendium where we present a few alternatives for the ones interested, I'll make a PR about this soon with a rough draft
