### ISSUE TITLE
review new version of javatex

### ISSUE THREAD

**Issue by bjornregnell** [lunduniversity/introprog#429]
A new version of the javatext lab is available on page 384 in this pdf:
https://fileadmin.cs.lth.se/pgk/compendium.pdf
You can see the differences here:
https://github.com/lunduniversity/introprog/commit/ea95a9241f38108da362c8b652d3c59c6aba7224

**Comment by bjornregnell** [comment]
@jos-rosenqvist-3812 I plan to make the game time measurement optional (reqt 4 in current version), as it connects to saving on file. Do you see any problems with doing that?

**Comment by bjornregnell** [comment]
@jos-rosenqvist-3812 new version committed here: https://github.com/lunduniversity/introprog/commit/58c342302fe61072d003b730f84da3d2d910b09a

**Comment by jos-rosenqvist-3812** [comment]
It's possible to implement the time requirement without implementing saving to a file. I don't have anything against taking that requirement out, though. For me, whether the requirement should be kept or not is only a matter of how long we want the lab to take, and maybe it would be good to reduce it even further – but that's hard for me to say for sure before the students actually have tried out the new version of the lab.

But I would like to ask, are you planning to remove `getElapsedTimeMs()` from the `Game.java` specification as part of doing this? It would probably be good to do that so as to not confuse those who aren't going to implement it, but then again, I don't want anyone who wants to implement it to think that you can't add a method like that just because it isn't in the specification.
