### ISSUE TITLE
paramValue not explained

### ISSUE THREAD

**Issue by AntiSC2** [lunduniversity/introprog#445]
In project ImageProcessing, paramValue is referenced but not explained at all:

> Använd paramValue för att ge Random-objektet ett seed. På så sätt kan du återskapa bilden genom att applicera krypteringsfiltret igen, med samma paramValue, på den numera krypterade bilden.

I'm unsure how paramValue should be used and it doesn't make much sense to me. The program I'm writing has a Terminal UI but no where does it mention if the user should be able to enter the value for the filter, or if it's meant only to be changed in code.

**Comment by bjornregnell** [comment]
@AntiSC2 Yes, this is an inconsistency caused by left-overs from the good old Java days, where a Swing GUI had exactly one paramValue that was used by several filters. But now we have a terminal UI and we can have as many parameters to filters as we like :)  This should be changed and the talk about paramValue deleted. PR welcome.
