### ISSUE TITLE
snake rules feel "unusual"

### ISSUE THREAD

**Issue by jos-rosenqvist-3812** [lunduniversity/introprog#451]
This is not an especially serious issue, but I'm submitting it just in case...

The rules of the game implemented in the snake lab are somewhat different from the Snake rules that I imagine that most of the current generation of students would be used to. I would say that the most influential Snake games for this generation are Nokia's Snake II, and (probably to a lesser degree) Nokia's original Snake.

Nokia's Snake has the following rules:
* When you eat food, you get a point, the snake gets longer, and one new piece of food appears
* You die when you touch a screen edge

Nokia's Snake II has the following rules:
* When you eat food, you get a point, the snake gets longer, and one new piece of food appears
* For every fifth piece of food you eat, a bonus item shows up, which disappears after a short time, gives points if eaten, and does not make the snake grow
* You wrap around when you touch a screen edge

While I don't have anything at all against not having the bonus items implemented, there are some game rules in the snake lab that just feel weird to me as someone who mainly has played Snake II, like the snake growing on its own after a set amount of time.

**Comment by bjornregnell** [comment]
Thanks for pointing this out! I'm used to snake ("masken") on ABC80 from the 1980:ies so I'm definately a dinosaur :).
Perhaps the Nokia rules could be part of the non-mandatory suggestions and if current rules is too much of an itch to contemporary students then they might be even more inclined to implement more or different rules... So my suggested fix for this issue is to include this in the optional requirements part. Removing the "grow" function impacts also exercises and I think "grow" is a nice exercise on sequences. But we could move "grow" to the optional reqts, making the mandatory part significantly easier. What do you think @jos-rosenqvist-3812 ?

**Comment by bjornregnell** [comment]
I'm marking this low priority for now, as the change is a bit risky while the print deadline is approaching. Let's consider changing this when we get to the Scala 3 major overhaul, if that's ok?

**Comment by jos-rosenqvist-3812** [comment]
I agree.

**Comment by bjornregnell** [comment]
As there is now both Banan and Apple we will use our own snake rules, so closing this.
