### ISSUE TITLE
Update for scala 3docs

### ISSUE THREAD

**Issue by M0R60TH** [lunduniversity/introprog#600]
In the exercises for week 4, specificallt exercise 7b, we are told that we can go from the documentation directly to the source with a button. This is no longer the case in scala 3. Should this be updated, possibly with a link to the source as well?

**Comment by bjornregnell** [comment]
Yes but need to find out how to do it in scaladoc 3. This is an issue for the other repo: 
https://github.com/lunduniversity/introprog-scalalib/issues/28
So this isssue should be closed when fixing that. Should be fixed in the api doc build using sbt with som setting I guess but don't know how yet...

**Comment by Husenap** [comment]
This issue can now be closed as it has been fixed.
