### ISSUE TITLE
Remove references to SBT from lab words

### ISSUE THREAD

**Issue by axelnilsson98** [lunduniversity/introprog#771]
Remove references to sbt from lab words and make it not mandatory since scala-cli now is the main way to compile and run projects in the course

**Comment by valterbergstrand** [comment]
Is it wrong to call scala-cli a build tool? Is there a better way to define it? I am working on a PR for this issue

**Comment by bjornregnell** [comment]
> Is it wrong to call scala-cli a build tool? Is there a better way to define it?

The scala-cli is limited build tool that can't have sub-builds like sbt and sbt can do much more. But since scala-cli will eventually be the official `scala` commmand I'd like to call scala-cli the "Scala runner" or the "Scala CLI" or the "Scala command line interdace" in swedish "körverktyg", "kommadoverktyg", but it is not wrong to call it a build tool as it builds executables. See official terminology here https://scala-cli.virtuslab.org/

**Comment by bjornregnell** [comment]
Fixed by: https://github.com/lunduniversity/introprog/commit/ad53f864a457301f30f5744ec91414e9dcc5f126
